baseURL = "http://docs.thedesk.top/"
languageCode = "ja-jp"
defaultContentLanguage = "ja"
title = "TheDesk documentation"
pygmentsCodeFences = true
pygmentsStyle = "dracula"
metaDataFormat = "yaml"
paginate = 100
enableGitInfo = true

[menu]
  [[menu.docs]]
    name = "インストールする"
    weight = 10
    identifier = "install"
    url = "/install/"
  [[menu.docs]]
    name = "基本的な使い方"
    weight = 20
    identifier = "basic"
    url = "/basic/"
  [[menu.docs]]
    name = "投稿"
    weight = 30
    identifier = "post"
    url = "/post/"
  [[menu.docs]]
    name = "タイムライン"
    weight = 40
    identifier = "timeline"
    url = "/timeline/"
  [[menu.docs]]
    name = "タイムライン上のトゥート"
    weight = 50
    identifier = "toot-on-tl"
    url = "/toot-on-tl/"
  [[menu.docs]]
    name = "ユーザー情報"
    weight = 60
    identifier = "user"
    url = "/user/"
  [[menu.docs]]
    name = "アカウント"
    weight = 70
    identifier = "account"
    url = "/account/"
  [[menu.docs]]
    name = "メニュー"
    weight = 80
    identifier = "menu"
    url = "/menu/"
  [[menu.docs]]
    name = "設定"
    weight = 90
    identifier = "settings"
    url = "/settings/"

[languages]
  [languages.ja]
    contentDir = "content/ja"
    languageName = "日本語"
    weight = -99